import { Box, Button, Stack, Typography, useMediaQuery } from "@mui/material";
import React from "react";
import { FlexBox } from "../../components/FlexBox";
import { shades } from "../../theme";
import Input from "../../components/Input";
import Posts from "../../components/Posts";
import { shallowEqual, useDispatch, useSelector } from "react-redux";
import { getRandomPrompt } from "../../utils/getRandomPrompt";
import { updateForm } from "../../state/formSlice";
import PaginationBtns from "./PaginationBtns";
import { useNavigate } from "react-router-dom";

// New image imports
import firstImg from "../../assets/First.png";
import secondImg from "../../assets/Second.png";
import thirdImg from "../../assets/Third.png";
import fourthImg from "../../assets/Fourth.png";

// Import MLModels component
import MLModels from "../mlmodels/MLModels";

const Home = () => {
  const isMobile = useMediaQuery("(max-width:767px)");
  const dispatch = useDispatch();
  const navigate = useNavigate();

  const { posts, status } = useSelector(
    (state) => state.postsReducer,
    shallowEqual
  );
  const { user } = useSelector((state) => state.userReducer, shallowEqual);

  const handleSurpriseMe = () => {
    const randomPrompt = getRandomPrompt();
    dispatch(updateForm({ prompt: randomPrompt }));
  };

  return (
    <Box padding={{ xs: "20px 5%", md: "50px 5%" }}>
      {/* Model Information Section */}
      <Box mb={4} textAlign="center">
        <Typography
          variant="h2"
          gutterBottom
          sx={{
            fontWeight: "bold",
            color: shades.primary[400],
            backgroundColor: "#f5f5f5", // light highlight background
            padding: "10px",
            borderRadius: "8px",
          }}
        >
          Regression-based Deep-learning Model
        </Typography>
        <Typography variant="body1">
          A regression-based deep-learning model, through adequate training, is extended to martensite-austenite (MA) island in bainite microstructure. The detection accuracy, estimated through mean Average Precision (mAP), is 98% for 0.5 IoU (Intersection over Union). The tool works best for gray scale 4000x scanning electron microscopic images of bainite.
        </Typography>
        <Typography variant="body2" color={shades.primary[300]} mt={2}>
          Few examples along with ground truth are shown below:
        </Typography>
      </Box>

      {/* Display MLModels just below the navbar */}
      <MLModels />

      {/* Community Showcase Section */}
      <Box textAlign={user ? "left" : "center"} mt={{ xs: "60px", md: "90px" }}>
        <Typography mb="5px" variant="h3">
          The Community Showcase
        </Typography>
        <Typography variant="small" color={shades.primary[300]}>
          Browse through a collection of imaginative and visually stunning images generated by microSdetect by theoRmets
        </Typography>
      </Box>

      {/* New Images Display Section : Will have to confirm with sir*/}
      {/*<Box*/}
      {/*  display="flex"*/}
      {/*  justifyContent="center"*/}
      {/*  alignItems="center"*/}
      {/*  mt={{ xs: 2, md: 4 }}*/}
      {/*  flexWrap="wrap"*/}
      {/*>*/}
      {/*  <Box m="10px">*/}
      {/*    <img*/}
      {/*      src={firstImg}*/}
      {/*      alt="first"*/}
      {/*      style={{*/}
      {/*        width: "25vw",*/}
      {/*        height: "25vw",*/}
      {/*        objectFit: "cover",*/}
      {/*      }}*/}
      {/*    />*/}
      {/*  </Box>*/}
      {/*  <Box m="10px">*/}
      {/*    <img*/}
      {/*      src={secondImg}*/}
      {/*      alt="second"*/}
      {/*      style={{*/}
      {/*        width: "25vw",*/}
      {/*        height: "25vw",*/}
      {/*        objectFit: "cover",*/}
      {/*      }}*/}
      {/*    />*/}
      {/*  </Box>*/}
      {/*  <Box m="10px">*/}
      {/*    <img*/}
      {/*      src={thirdImg}*/}
      {/*      alt="third"*/}
      {/*      style={{*/}
      {/*        width: "25vw",*/}
      {/*        height: "25vw",*/}
      {/*        objectFit: "cover",*/}
      {/*      }}*/}
      {/*    />*/}
      {/*  </Box>*/}
      {/*  <Box m="10px">*/}
      {/*    <img*/}
      {/*      src={fourthImg}*/}
      {/*      alt="fourth"*/}
      {/*      style={{*/}
      {/*        width: "25vw",*/}
      {/*        height: "25vw",*/}
      {/*        objectFit: "cover",*/}
      {/*      }}*/}
      {/*    />*/}
      {/*  </Box>*/}
      {/*</Box>*/}

      <Posts {...{ posts, status, community: true }} />
      <PaginationBtns />
    </Box>
  );
};

export default Home;
